apiVersion: v1
kind: PersistentVolume
metadata:
  name: featureflag-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # Manuel bağlama; StorageClass kullanılmıyor
  hostPath:
    path: /var/log/featureflag-pv
    type: DirectoryOrCreate
  # Opsiyonel: PV'yi belirli bir node'a sabitlemek için aşağıdaki nodeAffinity'yi ekleyebilirsin.
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - "node-1"   # Hedef node hostname