apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: featureflag-logs-pvc
  namespace: storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi